### ISSUE TITLE
Adicionar subnotificação de casos no modelo

### ISSUE THREAD

**Issue by JoaoCarabetta** [ImpulsoGov/simulacovid#31]

**Comment by fernandascovino** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Criação Modelo V_2](https://trello.com/c/GMn6sYvb/16-cria%C3%A7%C3%A3o-modelo-v2)

**Comment by fernandascovino** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Criação Modelo V_2](https://trello.com/c/GMn6sYvb/16-cria%C3%A7%C3%A3o-modelo-v2)
