### ISSUE TITLE
Adicionar atualização dos Embaixadores

### ISSUE THREAD

**Issue by JoaoCarabetta** [ImpulsoGov/simulacovid#59]

**Comment by JoaoCarabetta** [comment]
@gabrielsaruhashi 

adicionei os dados dos embaixadores somente para leitos e ventiladores.

Como obter os dados está comentado aqui https://github.com/ImpulsoGov/simulacovid/blob/5cb03eeb2fb568fa2625c897c9b7e7433c156ca5/src/simulation.py#L104

Quando selecionamos mais de uma cidade, podem existir várias fontes. Então, tem que ver como citar todos e ficar belo.

**Comment by fernandascovino** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Programa Embaixadores](https://trello.com/c/zm4gPk7f/10-programa-embaixadores)
